
FROM debian:buster-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    python3-dev \
    python3-cffi \
    python3-pip \
    libcairo2  \
    libpango-1.0-0  \
    libpangocairo-1.0-0  \
    libgdk-pixbuf2.0-0  \
    libffi-dev  \
    shared-mime-info \
    git \
    vim \
    openssh-client \
    curl \
    libblas-dev \
    liblapack-dev \
    gfortran \
    python3-opencv \
    python3-sklearn \ 
    libjemalloc-dev \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-system-dev \
    libboost-regex-dev \
    autoconf \
    flex \
    bison \
    python3-sphinx


RUN apt-get update \
    && apt-get -y install --no-install-recommends python3-wheel libssl-dev libhdf5-dev pkg-config protobuf-compiler cython3 \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip 
RUN pip3 install --no-cache-dir setuptools==54.0.0
RUN pip3 install --no-cache-dir https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_aarch64.whl
RUN pip3 install click importlib-resources notebook ipywidgets pandas pickle5 plotly pyarrow shap colorlog beautifulsoup4 imutils 


ARG USERNAME=sihihi
ARG USERID=1000
RUN useradd --system --create-home --shell /bin/bash --uid $USERID $USERNAME
USER $USERNAME
WORKDIR /home/$USERNAME/app
RUN echo "export LD_PRELOAD=" >> ~/.bashrc